ssec/polar2grid

doc/source/utilscripts.rst

Fix #164
We should regenerate the PDF and replace the existing one on the website.

Fix incorrect .txt extension on custom grid config examples

---

.travis.yml
polar2grid/avhrr/readers.py

@spruceboy brought this up over email. I looked in to the current version of the reader in Satpy and looks like some new checks have been added. In the future we'll be using Satpy directly, but for now this is an easy fix.

Fix the AVHRR reader not masking counts equal to 0

---

create_conda_software_bundle.sh

Closes #166
I also just learned that it seems GSHHG shapefiles are now available on conda-forge so in the future this may not be needed if `pycoast` can depend on this package instead: https://github.com/conda-forge/gshhg-gmt-feedstock

Fix readable permissions for bundled GSHHG shapefiles

---

polar2grid/core/containers.py
polar2grid/core/rescale.py
polar2grid/glue_legacy.py
polar2grid/readers/__init__.py
polar2grid/remap/remap.py

I ran in to this when working with VIIRS EDR Active Fires data where the data are integers and `0` is the implied fill value, but when remapping the data had NaN used in the output instead. This PR should fix various things about fill value handling including:
1. Use `_FillValue` if it is defined from Satpy
2. Use `fill_value` in nearest neighbor resampling
3. Pass attributes (`.attrs`) to palettize rescaling function

Fix fill_value handling for integer type data

---

polar2grid/remap/remap.py

Currently, using libraries that return float64 as the data type for arrays causes polar2grid to stall during cython code execution. This fix allows polar2grid to take more than just float32 as a data type.
Solved by @djhoese.

Fix ll2cr cols/rows not supporting 64-bit floats

---

polar2grid/crefl/crefl2swath.py
polar2grid/readers/__init__.py
polar2grid/viirs/io.py

The various VIIRS readers (crefl, viirs l1b, viir sdr) produce different names for the satellite/platform name that goes in the resulting output filename. This PR normalizes all of them to use "npp" for Suomi-NPP and "noaa20" for NOAA-20/JPSS-1. It should be relatively flexible and work with future noaa satellites following this naming structure.

Add satellite name normalization for NOAA-NN and SNPP satellites

---

polar2grid/remap/_fornav_templates.cpp

Linux on Travis is now using gcc 5.4 which is using C++11 by default. This is causing failures for fornavs compilation because there are cases where I pass an integer to `isnan` (a builtin function). In C99 this is a macro and returned False for integers, in C++11 this is a real function that only has signatures for floats/doubles. This is my simple fix.
@rayg-ssec It'd be great if you could sanity check this given my limited C++ knowledge.

Update fornav templates to work with C++11

---

NEWS.rst
NEWS_GEO2GRID.rst
doc/source/introduction.rst
polar2grid/glue.py

Closes #185.
This is for Geo2Grid 1.0.1. Some users needed to change the radius of influence for nearest neighbor resampling and I had forgotten to add this as an option.

Add --radius-of-influence flag for nearest neighbor resampling

---

polar2grid/readers/viirs_edr_active_fires.py
polar2grid/remap/remap.py

See #197 for details.
This changes `--grid-coverage` in to a parameter that can be set from readers, similar to `--fornav-d` and `--fornav-D`. This sets it to 0 for the viirs_edr_active_fires reader.

Set default grid_coverage for VIIRS Active Fires to 0

---

polar2grid/core/rescale_configs/rescale.ini

As mentioned in #197, it wasn't possible to create a colorized image of `confidence_pct` from the VIIRS EDR active fire reader in the latest polar2grid 2.3.0 alpha. This was because I forgot to configure it in the rescaling.
We should also configure something for `power`, @kathys is looking in to good values for this.

Fix VIIRS EDR Active Fires confidence_pct rescaling configuration

---

NEWS_GEO2GRID.rst
build_environment.yml
doc/source/grids.rst
doc/source/introduction.rst
polar2grid/core/containers.py
polar2grid/glue.py
polar2grid/grids/grids.conf

This PR adds one work around for #187.
This adds new GOES-based grids to the default builtin grids:
* goes_east_1km
* goes_east_4km
* goes_east_8km
* goes_east_10km
* goes_west_1km
* goes_west_4km
* goes_west_8km
* goes_west_10km
It also allows users to use `native` resampling by default if Geo2Grid detects that a grid is "native" compatible. This should not really change behavior for anyone unless they were already attempting to do what #187 talks about: resampling to a lower resolution version of the GOES grids. Note these new grids are only the full disk versions of these grids. I'm considering this a bug fix because it should have been possible for users to do this already.

Add ability to native resample to lower resolution grids

---

polar2grid/core/rescale_configs/rescale.ini
polar2grid/readers/__init__.py

Pointed out in our meeting today:
1. `confidence_pct` being from 0-100% results in `0` values (the most common value) being yellow which is different than `confidence_cat` which is transparent for non-fire pixels.
2. Fire `power` was not being scaled properly because I used the `reader` parameter in the rescaling configuration. The Satpy reader wrapping code was not assigning the `reader` in product metadata so this information was never getting to rescaling.
This PR should fix both of these cases.

Fix rescaling configuration for some active fires variables

---

polar2grid/gtiff_backend.py

Pointed out by @spruceboy in one of the alpha releases of polar2grid. I had fixed this for Geo2Grid's geotiff backend, but didn't realize it was also needed for Polar2Grid.

Fix gtiff backend not parsing dtypes correctly

---

polar2grid/core/rescale.py
polar2grid/core/rescale_configs/rescale.ini
polar2grid/gtiff_backend.py
polar2grid/readers/__init__.py

This one should actually fix #205 
In summary, I was making an LA geotiff where the L band had a color table added to it. The assumption was that the color table would color the L pixels and the A band would be able to tell us the transparency. That was not true. These are, as far as what I wanted them to look like, invalid geotiffs and are not recognized by most image viewers.
The solution is to generate RGBA images where each pixel has the colortable already applied to it. The Alpha band determines transparency and invalid pixels.
This PR also depends on some of the recent fixes in Satpy for the `power` dataset and how it has its `_FillValue` set.

Fix VIIRS Active Fires creating non-standard geotiff files

---

etc/composites/mersi-2.yaml
polar2grid/core/rescale_configs/rescale.ini

Fix MERSI-2 natural_color scaling and add false_color composite

---

polar2grid/readers/__init__.py

Closes #207 
This was a simple fix for a very complicated problem...
Polar2Grid uses a product's *name* (and only the name) to uniquely identify that product. Satpy uses name, resolution, calibration, and optional modifiers (among some other things). In certain cases, usually when composites need to be made with rayleigh correction or other modifiers applied, the "raw" band needs to exist along side the "modified" band at the same time. Polar2Grid internals do not currently handle this case since it would involve using more than just the name.
By passing `generate=False` to the Satpy Scene's `load` method, P2G tells it not to do any modifications/corrections or try to generate any composites until *after* resampling. After resampling we shouldn't need any of these modified datasets so …

Fix modified datasets causing duplicate cached files on disk

---

polar2grid/readers/mersi2_l1b.py
polar2grid/readers/virr_l1b.py

Closes #219 and Closes #220 
I was able to copy the logic used for VIIRS L1B to filter out reflectance products when there isn't a lot of day data in the scene.

Add day percentage filter to VIRR and MERSI-2 readers

---

polar2grid/readers/__init__.py
polar2grid/readers/mersi2_l1b.py
polar2grid/readers/viirs_l1b.py
polar2grid/readers/virr_l1b.py

Closes #223.
This is another one of those very complicated situations for such a simple feature. The previous implementation of daytime filtering ("we don't have a lot of day data, don't produce reflectance-based images") was able to fairly easily remove reflectance bands and hardcoded RGB composites (true_color, false_color, natural_color) from being generated. However, it wasn't updating the "wishlist" of products we want to generate so after resampling P2G was trying to generate things we knew we couldn't make any more. After trying to fix this I realized another issue was that if we said we can't make the true_color we had already loaded some of the dependencies needed for that composite but hadn't deleted them. So we might need the solar_zenith_angle to generate the true_color and no …

Fix daytime filtering when composites aren't generated yet

---

polar2grid/readers/__init__.py
polar2grid/readers/viirs_l1b.py

viirs_l1b.py was looking for standard_name where it should not have been. This is a work around that does not generate composites when composites should not be made.

Fix viirs_l1b standard_name Not Found

---

polar2grid/compositors/rgb.py
polar2grid/core/containers.py
polar2grid/glue_legacy.py

This was an issue that @kathys identified but had trouble nailing down the exact cause and reproducing it. She sent me a log for one such case and I have an idea for what's going on. Bottom line this should fix this issue.
Doing `del gridded_scene` in python (see code changes for this PR) is meant to delete the current gridded scene and let python's garbage collector remove things when it wants. As part of deleting the gridded scene, the flat binary files underneath should also be deleted (ex. `true_color.dat`). However, it seems that in some cases this is taking too long and causing issues. Mainly this happens when resampling to multiple grids. If we process grid 1, delete the gridded_scene, move on to process grid 2, we end up creating/using the same flat binary file as the first grid's …

Fix race condition when deleting multiple gridded scenes

---

polar2grid/glue.py
polar2grid/writers/geotiff.py

I recently discovered that rasterio (gdal), the library we use in satpy/trollimage to save geotiffs, allows for you to specify how many threads are used when compressing the image data. For slow compression algorithms like DEFLATE this can make a big difference in amount of time it takes to save the data to disk.
To enable this I needed to pass a `num_threads` keyword argument to Satpy. The easiest way to do this is to make a command line argument, but since this argument can easily default to the number of dask workers used (`--num-workers`) and in most cases shouldn't need to be defined by the user. So I've decided to hide the option and have it default to the number of dask workers.

Add option to enable geotiff multi-threaded compression and overview creation

---

polar2grid/readers/clavrx.py

This fixes an old masked array usage that slipped through the cracks when updating Polar2Grid to work with Satpy usage of xarray DataArray objects.
Addresses part of the problem in #236

Fix the clavrx reader using old Satpy masked array usage

---

polar2grid/remap/_ll2cr.c
polar2grid/remap/_ll2cr.pyx

Pyproj 2.4.2 changes the invalid transformation value from 1e30 to `inf`. In most cases checking for `>= 1e30` is sufficient, but this PR fixes the one case where I don't do that.

Fix ll2cr code compatibility with pyproj 2.4.2

---

polar2grid/core/rescale.py

Closes #244 
I had discovered in the past that the VIIRS Active Fire products were producing an LA + color table geotiff but this isn't actually a valid format. When I fixed this for fires I never actually fixed it for the VIIRS EDR Flood product which has a special rescaling/enhancement function. This PR fixes that.

Fix VIIRS Flood being an LA image when it should be L only

---

polar2grid/core/rescale.py
polar2grid/glue_legacy.py

@kathys noticed that the newest P2G beta tarball is producing a lot more warnings than it used to. This is caused by a new version of pyproj and there is no reason the user needs to see these.

Ignore library warnings in Polar2Grid glue script

---

NEWS_GEO2GRID.rst
doc/source/introduction.rst
swbundle/gtiff2mp4.sh

@kathys found in her testing that the "small" changes I made to `gtiff2mp4.sh` to accept geotiffs or PNGs as input wasn't working. I had a typo where I forgot the `$` in front of a bash variable usage. This fixes it and adds information about this PNG handling to the release notes.

Fix gtiff2mp4.sh not using a bash variable properly

---

NEWS_GEO2GRID.rst
doc/source/introduction.rst

Satpy had a change to how "tight" the day/night transition is by default. This PR makes sure to mention this in the release notes.

Add note about day/night transition change in G2G release notes

---

swbundle/env.sh

A recent mailing list post had issues with finding the NetCDF library. This made me think that they had `LD_LIBRARY_PATH` set which shouldn't have been a problem because the `env.sh` script is supposed to remove that. However, after looking I noticed that it only does this for the legacy ShellB3 builds of Polar2Grid. This PR fixes this by doing it for conda-based distributions too.

Clear LD_LIBRARY_PATH in conda-based distributions

---

polar2grid/crefl/crefl2swath.py

@kathys noticed that her operational processing was failing to create CREFL-based true and false color RGB composites. This was caused by the M-band longitude and latitude magically being deleted in the middle of processing. This PR fixes this.
Honestly, this is a workaround fix and not the "right way" to do this. However, this code won't be used much longer so no need to fix it the right way.

Fix race condition causing crefl to delete files during processing

---

doc/source/rescaling.rst

Closes #282. @jpnIII pointed out that the numbers didn't seem right in the linear rescaling example. This PR should fix these based on his suggestions.

Fix linear rescaling example numbers

---

NEWS_GEO2GRID.rst
doc/source/introduction.rst

We've been passing out a 1.0.2b0 out to people who needed it. Now with the plan to actually release it, the notes need to be updated to reflect the single change included in the release.

Update release notes for 1.0.2 release

---

.travis.yml
etc/composites/viirs.yaml

Newer versions of Satpy have restructured some of the default VIIRS composite/modifier configurations. This has a weird side effect for the custom configurations in Polar2Grid. For example, in Satpy the rayleigh correction is defined as "rayleigh_corrected" with hard "prerequisites" for the 4 angles needed. In Polar2Grid's older configuration it is also called "rayleigh_corrected" but had all "optional_prerequisites". With the way Satpy handles merging config files this resulted in rayleigh_corrected being defined with both the prereqs and the optional prereqs which was causing weird error messages. This PR should fix them by "coordinating" with the newer Satpy versions.

Fix VIIRS composite configuration to work with newer Satpy

---

polar2grid/mirs/mirs2swath.py

Added the necessary filename identifiers for Metop-C files in the MIRS reader.

Add support for Metop-C in MIRS reader

---

polar2grid/glue.py
polar2grid/readers/mirs.py

Part of change to address update of legacy MiRS reader mentioned in #269 and #151 might need checking.  Like the old reader, the new reader is only checking for missing values...
1. Adds a MiRS stub to the readers directory to work in combination with upcoming addition of MiRS reader in satpy.
2. Stub uses aliases similar to viirs_sdr.py
3. Default aliases checked in glue.py to existence of data id name in Scene object.  This adds a function which extracts the data name from the alias DataQuery and compares against the data names returned by the Scene.available_dataset_ids.  This should work even when readers do not use product aliases in the stub file, or if the list of product aliases contain strings.
glue checked with MiRS files for gpm and noaa satellites.  Glue checked with abi_l1b …

Add MiRS reader

---

polar2grid/resample/_resample_scene.py

Really bad bug that I should have caught (I know, we need tests) that was replacing any area provided by the user with the default target area.

Fix areas to resample to always being the default area

---

RELEASING.md
etc/composites/viirs.yaml
etc/enhancements/generic.yaml
polar2grid/enhancements/shared.py
polar2grid/filters/__init__.py
polar2grid/filters/_filter_scene.py
polar2grid/filters/day_night.py
polar2grid/glue.py
polar2grid/readers/viirs_sdr.py
polar2grid/resample/_resample_scene.py

Porting some functionality from legacy Polar2Grid to Polar2Grid 3.0 with pyresample features instead of forcing SZA to be loaded.
This adds a `--filter-day-products` and `--filter-night-products` flag to control if filtering based on amount of day/night should be done and how much day/night is needed for a day-only/night-only product to be generated (as a fraction of the overall Scene). This also uses a `--sza-threshold` flag to control where the transition point is between day and night as the angle in degrees (default 100).

Add day/night filtering using SZA

---

polar2grid/glue.py

To match old P2G, we're turning filtering on by default.

Change Polar2Grid to default to filtering day and night products

---

doc/source/writers/scmi.rst
polar2grid/glue.py
polar2grid/writers/awips_tiled.py

The `fix_awips` keyword argument has been deprecated (or will be) in the Satpy 'awips_tiled' writer. I had to do this because of some odd xarray/dask hanging I was experience and supporting this flag only complicated the matter. As far as I know this flag is no longer needed as all AWIPS workstations have been updated by the NWS and don't run into this bug anymore. The bug was that AWIPS was using an old version of HDF5/NetCDF4 for Java and it was unable to parse NetCDF files created with newer versions of the NetCDF4 library.

Hide '--fix-awips' flag as it is deprecated in Satpy

---

polar2grid/core/containers.py
polar2grid/grids/grids.conf
polar2grid/resample/_resample_scene.py

While helping a user I noticed a few things wrong with the resampling code in certain situations. I also noticed some old bugs in Polar2Grid grid handling code.
By helping the user I realized that we can probably get more accurate projection information in a geotiff if we omit the `ellps` in our `grids.conf` and only provide the `+datum`. Recent versions of PROJ seem to like this better. I've asked some pyproj folks about this to double check.

Fix resampling when areas and resampler are both provided

---

integration_tests/features/steps/compare_images.py
polar2grid/filters/_utils.py
polar2grid/resample/_resample_scene.py

The `Boundary` objects I'm using only need the outer lon/lat values of the swath. I was providing them with internal ones and it was causing some issues in the results and performance issues. This makes sure to only use the clockwise boundary coordinates.

Fix grid coverage checks not using swath boundaries properly

---

.gitignore
build_environment.yml
create_conda_software_bundle.sh
doc/source/_static/CSPP_Logo.png
swbundle/env.sh

Satpy now provides an interface for downloading additional data files. With Polar2Grid, we don't want this to happen at runtime; we want to download everything we're going to need before hand. This PR adds the basic logic to make this work. This will likely take many iterations to get perfect so that we are only including files that we really need. For example, there are composites in Satpy that download huge geotiff files but we don't use these composites. Similarly, should we include things like the MiRS lookup tables when we bundle Geo2Grid? Probably not, but I don't like the idea of these things only being included in one project and not the other. We'll see what kind of size increases we get.

Add Satpy auxiliary data download to bundle creation

---

etc/resampling.yaml

As pointed out in #326, VIIRS should have a fornav "d" flag of 2, but I had it as 1. This is likely a copy/paste error.

Fix default resampling parameters for VIIRS

---

etc/composites/viirs.yaml

This depends on newly added Satpy functionality. The Modifier in Satpy now downloads the CMGDEM.hdf file instead of defaulting to all 0s for the elevation dataset (if it can't find the file). This PR uses that functionality as well as the improved handling of putting a hard requirement on the angle datasets (previously optional which could cause issues in specific situations).

Update VIIRS crefl usage to download CMGDEM.hdf file

---

swbundle/env.sh

@kathys pointed out that doing `source $POLAR2GRID_HOME/bin/polar2grid_env.sh` fails in the latest tarball. I've added this to #326. The main issue is that the "real" file is `env.sh` and `polar2grid_env.sh` is just a relative softlink pointing to `env.sh`. The "magic" bash to locate the true location of the current script was not smart enough to handle this relative softlink situation so the rest of the script was trying to use an invalid location. This PR fixes that.

Fix error when sourcing bundle environment script

---

polar2grid/util/legacy_compat.py

Functions to convert legacy P2G keyword in output_patterns to new keywords.  Additions of deprecation warnings are needed.  data_kind is not included in the list.

Mapping old to new names for output_pattern

---

MANIFEST.in
build_environment.yml
create_conda_software_bundle.sh
etc/writers/binary.yaml
polar2grid/core/dtype.py
polar2grid/core/script_utils.py
polar2grid/glue.py
polar2grid/tests/__init__.py
polar2grid/tests/etc/enhancements/generic.yaml
polar2grid/tests/test_writers/__init__.py
polar2grid/tests/test_writers/test_binary.py
polar2grid/writers/binary.py
polar2grid/writers/geotiff.py

This re-adds (ports?) the binary writer to work with Polar2Grid 3.0 by making a satpy-compatible writer. This is an interesting conversion because I kind of disagree with the way the original writer was done. It had a few special cases for floating point data and for fill values. This version of the writer is a little more predictable and I *think* it mostly behaves the same. It now *always* enhances (old language: rescales) the data regardless of input or output data type (dtype). This *might* require some existing users (the 1 or 2 that there are, I assume) to add `--no-enhance` to their commands.

Add satpy-compatible flat binary file writer

---

polar2grid/glue.py

The old Polar2Grid flag (called "distance upper bound" I think) was in output grid units. This is no longer true. The units of `--radius-of-influence` are geocentric meters (essentially real world meters on the WGS84 model of the Earth). This is a result of switching to pyresample's implementation of nearest neighbor which converts input coordinates to geocentric X, Y, Z space to determine neighbor distances.

Fix description of --radius-of-influence units

---

integration_tests/features/polar2grid.feature
integration_tests/features/steps/compare_images.py
polar2grid/compare.py
swbundle/p2g_compare.sh

This adds a new set of tests for the MiRS reader with all of the common writers (binary, gtiff, hdf5, awips tiled). The original files were just added to the test directories on bumi by @kathys and by looking at the logs I've converted those commands to Polar2Grid 3.0 commands (the only change is the addition of the `--fill-value 0` on the geotiff line).

Add new MiRS integration tests

---

polar2grid/glue.py

The old MiRS and ACSPO readers were using "n20", but to be consistent we want "noaa20".

Fix inconsistent noaa20 platform naming for various readers

---

doc/source/readers/viirs_sdr.rst
etc/enhancements/abi.yaml
etc/enhancements/ahi.yaml
etc/enhancements/generic.yaml
etc/enhancements/viirs.yaml
integration_tests/features/steps/compare_images.py
polar2grid/compare.py
polar2grid/resample/_resample_scene.py
polar2grid/tests/test_writers/test_binary.py
polar2grid/writers/binary.py
polar2grid/writers/geotiff.py

To avoid inconsistencies as Satpy changes, the binary writer needs to have consistent output for floating point data. With current versions of xarray (this may change in the future) it is very easy for Satpy to accidentally upcast 32-bit floats to 64-bit floats. This amount of precision is unnecessary for most remote-sensing satellite instruments and wastes space and processing time. This PR makes it so instead of defaulting to the same data type as the input data, the writer will cast 64-bit floats as 32-bit floats. This way if Satpy or xarray changes in the future produce the same data as 32-bit floats, this won't change output for P2G users.
This PR also includes fixing output filenames for the geotiff and binary writers, fixing the default radiance enhancement configuration, and …

Change binary writer to default 64-bit floats to 32-bit floats

---

build_environment.yml
continuous_integration/environment.yaml
polar2grid/glue.py

This is an initial attempt to allow users to pass URLs to S3 files. It allows for `s3://` style URLs and assumes anonymous access is allowed. It also allows you to prefix with `simplecache::` (a feature of the `fsspec` python library) and it will cache the files locally and improves performance. Note that this caching will write to a temporary directory by default so it is up to the system/user to clear it out. There are many improvements and options that could be added.
To support this in Satpy with more flexibility a `FSFile` class was created to wrap `fsspec` open file objects. This PR takes advantage of this interface. There are others available to get S3 resources to xarray, but this is the only one that is currently available to Satpy.
FYI @rayg-ssec

Add ability to pass S3 URLs

---

polar2grid/utils/legacy_compat.py
polar2grid/writers/hdf5.py

HDF5 writer: Metadata Fixes: change grid projection string to the proj4_string, reverses cell height and adds x and y origin values.  Write the p2g_name to the files rather than the satpy name for the variables.  
Update the pattern conversion so that begin_time defaults to the format that was produced in the previous output_filename which is now start_time:%Y%m%d_%H%M.  start_time, when entered alone should still output the default date pattern which is in isoformat.

Fix various HDF5 writer issues

---

polar2grid/glue.py

I noticed while playing with the "awips_tiled" writer that if it doesn't find any valid data to write to files then the glue script crashes. This PR fixes it so there is no crash and also logs a warning letting the user know why this may have happened.

Fix execution when no output products will be produced

---

doc/source/readers/abi_l1b.rst

Scott Bachmeier pointed out that we were crediting CIRA with the creation of the night microphysics guide, but it was actually contributed by Kevin Fuell at NASA SPoRT.

Fix description of ABI L1b Night Microphysics RGB

---

etc/enhancements/generic.yaml
polar2grid/readers/clavrx.py
polar2grid/writers/binary.py
polar2grid/writers/geotiff.py

Update the Clavr-x wrapper referenced in #318.  A dictionary has been added with day/night products for filter following the viirs_sdr wrapper.  This means that the day/night product filter uses standard names rather than variable names.  Changes to wrapper are based on the example set in the viirs_sdr reader.  The Frontend class and group arguments have been removed.  The DAY_ONLY and NIGHT_ONLY variable names are still in the wrapper, but as far as I can tell, they are not used?  I am concerned that the standard_name for the  toa_bidirectional_reflectance is too general because channel 7 is a mixed solar and thermal and produces a product in both day and night hours.

Add proxy module for Satpy clavrx reader

---

etc/resampling.yaml
polar2grid/compare.py

This PR updates the reading of netcdf files to use mask and scale (previously set to false).  xarray.open_dataset replaces netcdf4.Dataset so that mask, scale and fill are handled when read.  
file_type and plot keywords did not seem to be used previously, or something went wrong with my version, this PR updates the use of the --plot and file_type arguments.
the comparison plots were nice, but sometimes hard to know how severe the differences are by just looking at side to side plot.  This adds a nanquantile subtitle to the plots and a plot difference of array1 - array2.
Updates needed for clavrx resampling were found when testing this version of compare, these are added in this PR.

Use mask_and_scale in comparison of netcdf

---

doc/source/examples/acspo_example.rst
doc/source/examples/amsr2_example.rst
integration_tests/features/environment.py
integration_tests/features/geo2grid.feature
integration_tests/features/polar2grid.feature
integration_tests/features/steps/compare_images.py
integration_tests/features/utilities.feature
integration_tests/run.sh
polar2grid/add_coastlines.py
polar2grid/add_colormap.py
polar2grid/compare.py
polar2grid/glue.py
setup.py
swbundle/add_coastlines.sh
swbundle/add_colormap.sh
swbundle/example_enhancements/amsr2_png/enhancements/generic.yaml

Currently it is only possible to have per-run config changes if the user manually changes the directory built into the polar2grid bundle (etc). This new `--extra-config-path` flag lets you specify one or more additional paths (can be specified more than once) with Satpy YAML configuration files.
This PR includes updating the AMSR2 example which used --rescale-configs so it now uses this new flag with a new enhancement configuration file.

Add --extra-config-path glue option and add_coastlines optional caching

---

integration_tests/run.sh
polar2grid/add_colormap.py

To match add_coastlines.py and my change to using rasterio instead of gdal, this changes add_colormap.py to use rasterio to access GDAL functionality.
Side note: It seems that `import gdal` no longer works and that I need to do `from osgeo import gdal` to get it to work.

Switch to rasterio in add_colormap.py script

---

polar2grid/glue.py

Some readers can add flags that modify `--products` results. Some don't though. The glue script didn't handle this properly.

Fix glue script when reader has no custom products flags

---

continuous_integration/environment.yaml
doc/source/conf.py
jenkins_environment.yml
polar2grid/filters/_utils.py

This causes issues when trying to compute polygon intersections in grid coverage filtering.
See https://github.com/pytroll/pyresample/pull/389

Backport pyresample fix for bbox lonlats being clockwise

---

etc/composites/viirs.yaml
polar2grid/readers/viirs_sdr.py

This was a flag in P2G 2.3, but I had missed it here. It really doesn't fit into how Satpy wants composites to work so what I've done is kind of hacky but it seems to work. Basically there are two versions of the dynamic_dnb composite (the other is `dynamic_dnb_saturation`) and when you specify the `--dnb-saturation-correction` flag the P2G code sees this and swaps the "alias" so `dynamic_dnb` points to `dynamic_dnb_saturation` but still gets called the same thing.

Add missing --dnb-saturation-correction flag to viirs_sdr reader

---

polar2grid/glue.py

As described in #326, the `modis_l1b` and `modis_l2` readers were missing from the listing. Additionally, the list of available writers thought it was providing writers for Geo2Grid so it didn't include all the historical writers of Polar2Grid.

Fix polar2grid.sh -h not listing all readers and writers

---

polar2grid/glue.py

Closes #415
```
Writing:
-w WRITER, --writer WRITER
Writer used to save datasets. Supported writers: geotiff, awips_tiled, binary, hdf5
```

Remove mention of using multiple writers from usage text

---

polar2grid/glue.py
polar2grid/readers/viirs_sdr.py
polar2grid/utils/legacy_compat.py

Closes #420
Currently this only implements the fix for the warning message. Summary of the problem is that the flag was causing the list of products to load to be `["dynamic_dnb", "dynamic_dnb"]` and then when P2G was looking up what name this might refer to in Satpy-land it was seeing it already had something looked up. Simple fix, but I made it in two places to be sure.
I still need to look into the black images.

Fix warning produced by --dnb-saturation-correction flag

---

polar2grid/filters/_base.py
polar2grid/filters/resample_coverage.py
polar2grid/glue.py
polar2grid/resample/_resample_scene.py
polar2grid/tests/conftest.py
polar2grid/tests/test_resample/test_resample_scene.py

Closes #423 
This PR includes three major changes as far as code and execution go:
1. Adds a hidden `--create-profile` which when specified creates an HTML document (in the local directory by default) of dask diagnostics plots including a task stream, a CPU/memory resource plot, and a dask cache plot. This is basic information needed to identify major performance issues in the execution of the main glue script.
2. Refactors the filtering logic so that coarser resolution grids are processed first. Using this I also made the grid coverage calculations cache results based on (platform name, sensor name). This means that the coarsest resolution area/grid of a single execution is checked for resampling coverage first and then that percentage of coverage is used for all other bands. This …

Optimize grid coverage checks and avoid checks with certain dynamic grids

---

build_environment.yml
etc/resampling.yaml

While debugging other issues related to resampling, @kathys and I noticed that the default resampling configuration for ACSPO SST and seadas_l2 products were not specific to the instruments. All bands were being resampled using VIIRS weighting when MODIS (or AVHRR) have different settings. This PR adds those missing configuration settings.

Fix seadas_l2 and acspo resampling defaults not being instrument-specific

---

polar2grid/enhancements/shared.py
polar2grid/readers/viirs_sdr.py
polar2grid/tests/conftest.py
polar2grid/tests/test_enhancements.py
polar2grid/tests/test_glue.py
polar2grid/tests/test_resample/test_resample_scene.py
polar2grid/tests/test_writers/test_hdf5.py

Includes fixes to the `temperature_difference` enhancement which Closes #427
This PR updates the VIIRS reader so it doesn't accidentally clear the default product list so only dynamic_dnb is created. The fix itself is rather small, but as part of this I added much more complex tests which should allow for better testing of VIIRS related functionality in the future. Closes #441

Fix --dnb-saturation-correction flag clearing default product list

---

etc/enhancements/modis.yaml
polar2grid/readers/modis_l1b.py

This has to be in the command line so it automatically gets passed to Satpy to turn off masking of saturated pixels. Closes the saturated portion of #422. I will try to find a pretty way to hide it.

Add command line option to mask saturated modis_l1b band 2 pixels

---

doc/source/readers/avhrr.rst
integration_tests/features/polar2grid.feature
polar2grid/_glue_argparser.py
polar2grid/glue.py
polar2grid/writers/geotiff.py

Satpy uses the name `avhrr-3`. For backwards compatibility we need it to be `avhrr`. This PR adds aliases for sensors in the glue script. It also updates the name of the avhrr reader in all of the documentation to match the satpy one and lists the avhrr reader in the usage text.

Fix AVHRR reader using "avhrr-3" name instead of "avhrr"

---

polar2grid/core/containers.py
polar2grid/tests/test_grids/test_manager.py

While working on one of the integration tests I discovered that legacy grids with negative pixel resolutions (very common for legacy `y` resolutions), the resulting "frozen" AreaDefinition had a negative shape. A negative resolution in the sense that the area/grid ends up being flipped is almost never actually desired. It is rare enough that I'm removing the option of making a dynamic grid with a negative resolution. The resolution is forced to a positive value (`abs`).

Fix legacy dynamic grids not working with negative resolutions

---

swbundle/env.sh

In order to activate the environment in swbundle/env.sh, METADATA_CHECKSUM  is set using openssl. However, since the environment is not activate yet, it cannot find openssl on all systems (rockylinux:8 docker image). This merge points to the packaged environment's openssl directly.

Fix bundle initialization to use embedded openssl

---

create_conda_software_bundle.sh
swbundle/GEO2GRID_README.txt
swbundle/POLAR2GRID_README.txt

@joleenf pointed out on slack that the G2G beta tarball I gave her contained the Polar2Grid README and release notes. This PR fixes this issue. The main problem was that the swbundle creation script assumed the name of the software bundle was a single filename and not a path. If the path contains "polar" anywhere in it then the script thinks it is generating Polar2Grid instead of Geo2Grid. This ultimately isn't a big deal functionality-wise, but does matter for these smaller things like the README and release notes.

Fix bundle creation not creating geo2grid properly

---

doc/source/custom_grids.rst
polar2grid/_glue_argparser.py
polar2grid/glue.py

Currently swath definitions in a dynamic grid workflow will compute longitude and latitude dask arrays 3 times:
1. Day/night product filtering
2. Dynamic grid freezing
3. Resampling
This PR adds a default behavior (with hidden flag to disable) that persists all lon/lat arrays in memory after loading. This allows all these steps to use the data that is in memory for faster performance, but at the cost of higher memory usage.

Add optimization to persist swath definition lon/lat arrays

---

polar2grid/readers/ahi_hsd.py

Some users would like more control over the edge of the disk for AHI HSD data. There is a flag in satpy to control the default behavior of masking space pixels. Masking space pixels saves on output image size and rarely includes a lot of useful data (especially for people wanting to view Earth observations from Earth-observing satellites :wink: ). The new flag turns this behavior off.

Add --no-mask-space flag to AHI HSD reader

---

polar2grid/filters/day_night.py
polar2grid/glue.py
polar2grid/resample/_resample_scene.py
polar2grid/tests/conftest.py
polar2grid/tests/test_glue.py
polar2grid/tests/test_resample/test_resample_scene.py

In an effort to improve #423, I noticed that the swath persisting logic implemented in #472 wasn't actually holding on to the persisted data. It was a simple logic bug, but an important one. It meant that the lon/lats were being persisted (computed) but then immediately discarded and never used. So it basically did each geolocation load and interpolation at least one extra time more than it had to.

Fix persisting geolocations not actually persisting

---

polar2grid/writers/cf.py

Meant to resolve issue #471.  
1. The DEFAULT_OUTPUT_FILENAMES are wrong if an alternate engine is used.  What is the best way to deal with this in polar2grid...no default?
2. The boolean options are reversed for glue.  Most use a flag that negate the satpy flag.  Is there a better way to deal with this.
3. Command line dictionaries get pretty ugly in the glue.py call.  Is there a preferred way to deal with this in polar2grid?
ex.). python ~/code/polar2grid/polar2grid/glue.py -r clavrx -w cf -f /Users/joleenf/data/p2g/clavrx/meso/clavrx_OR_ABI-L1b-RadC-M6C01_G16_s202212419011712.level2.nc -g WGS84_MESO --grid-configs mygrid.conf -p cld_press_acha cld_temp_acha --groups "{\ \"WGS84_MESO\\": [\\"cld_press_acha\\", \\"cld_temp_acha\\"]}" --method nearest -vvv

Add CF-complaint NetCDF writer (cf)

---

etc/composites/viirs.yaml
polar2grid/readers/agri_l1.py

AGRI doesn't have a C15 and C16. Some of the wavelengths were wrong too.

Update AGRI L1 available products

---

build_environment.yml
etc/writers/awips_tiled.yaml
polar2grid/_glue_argparser.py
polar2grid/glue.py
polar2grid/resample/_resample_scene.py

Adds `--antimeridian-mode` for when dynamic grids are converted to static grids and the input data crosses the lon/lat antimeridian (-180/180). This currently only affects lon/lat projections (not mercator, not polar-stereographic, etc). It defaults to backwards Polar2Grid compatibility via `modify_crs`. Other options are `modify_extents` and `global_extents`. See pyresample `DynamicAreaDefinition.freeze` method documentation for more information.
This PR also includes #492.

Add --antimeridian-mode for dynamic grid handling

---

etc/resampling.yaml

It has been decided that the images look better with these settings even though they don't necessarily match up with the expected sensor properties.

Revert ACSPO resampling defaults to v2.3 settings

---

polar2grid/_glue_argparser.py

This flag currently doesn't work for swath based products (Satpy/pyresample can't do it without hurting performance) so it was decided that it would just be better to hide the option for Polar2Grid.
Closes #500

Hide --ll-bbox CLI option for Polar2Grid

---

polar2grid/add_coastlines.py
polar2grid/tests/test_add_coastlines.py

This PR fixes an issue that has existed since changes were made to colormap'ing in Satpy/Polar2Grid. There was a change made in trollimage that added scaling and offset information and eventually included a new `colormap` tag with a CSV version of the colormap that was applied. If the colormap is added with `add_colormap.sh` (what I would consider a "legacy" way of doing this), then that attribute is not available. In both of these cases where the geotiff has a colormap built in the add_coastlines script thought scale factor and offset were based on a 0 to 1 scale. This was the original way that trollimage was going to work with these attributes but was changed last minute and apparently I never updated polar2grid to reflect this.

Fix add_coastlines.py using the wrong colorbar limits when geotiff contains a colormap

---

create_conda_software_bundle.sh
polar2grid/_glue_argparser.py
polar2grid/glue.py
polar2grid/readers/mirs.py
polar2grid/tests/conftest.py
polar2grid/tests/test_glue.py
polar2grid/writers/hdf5.py
swbundle/download_pyspectral_data.sh

* `--extra-config-path` can now receive a single YAML enhancement file. A temporary directory will be made, the file will be renamed to `generic.yaml`, and the temporary directory will be used as an additional Satpy configuration directory. Closes #506 
* Add missing `--bt-channels` flag to mirs reader. Closes #512 
* Fix HDF5 writer `--compress` flag not working.
I really should have made these separate PRs but I got lazy.

Add ability to specify single enhancement YAML to --extra-config-path and other fixes

---

polar2grid/tests/test_utils/test_legacy_compat.py
polar2grid/utils/legacy_compat.py
polar2grid/writers/awips_tiled.py
polar2grid/writers/binary.py
polar2grid/writers/geotiff.py

This PR adds some backwards compatibility for people who used the old (and removed) `--filename-pattern` command line flag. This flag has been renamed `--output-filename` to be more clear about what it is, but now also uses Satpy-based metadata. This PR adds an extra step in this output naming by renaming old filename-pattern elements (ex. `grid_name`) to map to the new naming (ex. `area.area_id`). This mostly already existed thanks to @joleenf, but this PR adds it for more writers.

Fix backwards compatibility for --output-filename in more writers

---

.pre-commit-config.yaml
polar2grid/glue.py
polar2grid/readers/_base.py
polar2grid/readers/viirs_sdr.py
polar2grid/utils/legacy_compat.py

Closes #505 
Here is my best attempt at doing what is described in #505. @kathys I think we'll have to talk about what products actually show up in standard versus custom products. Maybe I need to add a new category of "hidden" products. Hopefully the examples below show what I mean. I talked with @scottlindstrom and he suggested that user products should go first, then satpy (in the `--list-products-all` case), then standard products.
Questions:
1. If there are no products available the P2G standard products will list `<None>` under the section header. Should it do that for the other sections. For now, after talking to Scott again, I think the sections should always be there with the indication that there are no products.
```
$ polar2grid.sh -r viirs_sdr -w geotiff -f …
```

Add user custom products to --list-products output

---

polar2grid/readers/viirs_l1b.py

It was using satpy naming like "I01" so the output filenames had "I01" in them instead of "i01" as is preferred for P2G.

Fix VIIRS L1B reader using satpy names for default products

---

etc/resampling.yaml

Includes using EWA with maximum weight mode for category products.
Closes #518. CC @joleenf who may be affected by these changes. These changes are meant to mimic Polar2Grid 2.3 behavior. They may be updated to produce better results in the future. Additionally, these current changes only affect swath-based products.

Fix clavrx not having correct default resampling for all products

---

etc/resampling.yaml
polar2grid/filters/_utils.py
polar2grid/filters/day_night.py
polar2grid/glue.py
polar2grid/readers/clavrx.py
polar2grid/resample/resample_decisions.py
polar2grid/tests/_avhrr_fixtures.py
polar2grid/tests/_fixture_utils.py
polar2grid/tests/_viirs_fixtures.py
polar2grid/tests/conftest.py
polar2grid/tests/test_filters/__init__.py
polar2grid/tests/test_filters/test_utils.py
polar2grid/tests/test_resample/test_resample_scene.py
polar2grid/utils/legacy_compat.py

Fixes include:
1. Fixing the handling of CLAVRx's rows of NaNs in geolocation data.
2. Fix AVHRR resampling configuration being used incorrectly. Note though that the 40:1 used for CLAVRx and 10:1 used for AVHRR L1b both produce holes on the edges of swaths in some data cases.
3. Other code cleanup and typos
Should address some of the issues in #520, and completely close #517.

Fix various AVHRR and CLAVRx data handling bugs

---

etc/resampling.yaml
polar2grid/readers/mersi2_l1b.py

Addresses some of the issues in #534. Specifically there was no resampling config for the MERSI-2 sensor and `natural_color` was listed as a default product when it should only be an "available" product.

Fix MERSI-2 resampling config and remove natural_color as default product

---

build_environment.yml
polar2grid/add_coastlines.py
polar2grid/tests/test_add_coastlines.py

Closes #439 
As described in the related issue, there is no need for --colorbar-vertical to exist as it can be inferred from the position of the colorbar (top, bottom, left, right). This PR removes the usage of it but doesn't remove the flag so it doesn't completely break people's scripts.
This PR also re-enables the default colorbar to be a grayscale colormap. This could be a problem if users think their non-linearly scaled data should have a linear colormap, but I think that's up to the user. @kathys what do you think: If I did a square root enhancement on VIIRS I01 and then ran add_coastlines.sh I'd be get a black->white colormap with the tick labels being 0 to 255.

Deprecate --colorbar-vertical in add_coastlines

---

polar2grid/glue.py
polar2grid/tests/test_glue.py

Closes #546 
This is a simple fix for the problem described in the related issue. Basically the user custom path was being applied before the polar2grid builtins were applied rendering them useless in any cases where the configurations matched.

Fix extra config paths being handled in the wrong order

---

build_environment.yml

Bump the versions of pyspectral, python-geotiepoints, and trollimage to their newest versions.
Pyspectral fixes a bug where it wasn't able to find the MERSI-2 RSR files.
The python-geotiepoints update includes the cython/optimized versions of the MODIS interpolation.
The trollimage update includes fixing colormap/colorizing for category/integer datasets.
NOTE: At the time of writing the geotiepoints conda-forge package is not available.

Update various dependencies in the software bundle

---

polar2grid/filters/_utils.py

Closes #421 
It seems there was no special handling of swaths where for one reason or another some coordinates were NaN (MODIS bow-tie possibly?). This is a simple fix where we detect these NaNs and force a computation of the entire lon/lat arrays to compute a bounding box for the swath.

Fix day/night coverage checks when lons/lats contain NaN

---

polar2grid/_glue_argparser.py
polar2grid/readers/modis_l1b.py
polar2grid/readers/modis_l2.py

This allows for the filtering to be completely skipped, potentially saving processing time.
This also includes an increase in the default MODIS chunk size for better performance.

Update --filter-day/night-products flags to allow for "false"

---

etc/readers/mirs.yaml

It was discovered that the new LUTs used in Satpy's MiRS reader product bad results when applied to SNPP, but only over land (NOAA-20 is fine):
The same image processed with v2.3 looks like:
The LUTs being used were published on [Zenodo](https://zenodo.org/record/4472664/) by @joleenf received from the original limb correction author. This pull request customizes the MiRS reader to use the LUTs from the P2G v2.3 release stored in github.
@kathys We should add it to the TODO list to contact the original authors and see what they have to say about this. Maybe they have new LUTs.

Force MiRS reader to use limb-correction LUTs from P2G v2.3

---

create_conda_software_bundle.sh
polar2grid/compare.py
polar2grid/filters/resample_coverage.py
polar2grid/glue.py
polar2grid/grids/manager.py

Kathy noticed that the custom MiRS LUTS we're using weren't being included in the swbundle tarball. This was because the Satpy utility script wasn't being told about the custom P2G YAML configs where the LUTs to use were being modified.

Fix software bundle creation not including P2G custom configs during aux download

---

etc/writers/hdf5.yaml

This isn't normally a problem since P2G always provides one from the command line arguments, but some Satpy utility scripts need to be able to create the writer without any additional arguments (like downloading auxiliary data).

Fix HDF5 writer not having a default output filename

---

integration_tests/features/steps/compare_images.py

Was checking for the existence of `true_color\n` when I should have been checking for `\ntrue_color\n`. This only affects the integration tests, not actual running code.

Fix integration tests not being specific enough when listing products

---

etc/writers/awips_tiled.yaml
polar2grid/readers/modis_l1b.py

@kathys pointed out that MODIS band products in AWIPS were showing up as "7" instead of the expected wavelength value. This was caused by the products not matching the proper AWIPS configuration section in the writer YAML. Satpy writer configs will need the satpy-specific product name and not the P2G alias for that product (satpy doesn't know about those aliases).

Fix MODIS AWIPS configuration using wrong product names

---

integration_tests/features/environment.py
integration_tests/features/polar2grid.feature
polar2grid/compare.py

I noticed the different number of pixels percentage wasn't accurate (said 100%) when there were any differing pixels. This PR makes it more accurate along with a couple other changes.

Fix compare script HTML not having a pixel percentage on failure

---

polar2grid/core/script_utils.py
polar2grid/readers/abi_l1b.py
polar2grid/readers/ahi_hsd.py
polar2grid/writers/awips_tiled.py
polar2grid/writers/geotiff.py

This flag (on by default) removes negative radiances and therefore NaN brightness temperatures. These show up in RGBs that use them, but does not solve what I had hoped it would solve as described in #499. The night_microphysics's use of C07 and the green pixels that show up are inevitable due to how C07 works. Not much we can do about that. This PR does still fix some black pixels in the RGB though.

Add `--clip-negative-radiances` flag to ABI L1b reader

---

polar2grid/add_coastlines.py
polar2grid/tests/test_add_coastlines.py

Closes #627
I at first tried to copy all tiff tags, but since some of them correspond to actual properties about the image data (number of bands, color scheme, etc) this doesn't work since we often convert L band images to RGB/A images. For now it is a simple check to only do higher numbered tags (usually geotiff-based tags).

Add ability to create geotiffs with add_coastlines

---

etc/enhancements/abi.yaml
etc/enhancements/agri.yaml
etc/enhancements/ahi.yaml
etc/enhancements/ami.yaml

Replaces #641. Closes #278. After talking with @jpnIII and others in the NOAA Imagery team, we think it would be best to match AWIPS rather than do the 3 range piecewise function suggested in #278 and implemented in #641. AWIPS does a simple linear scaling from 127C to -109C. I added 273.15 to these values and put them in the YAML for ABI.
@jpnIII and @scottlindstrom Does it make sense to apply this change to AMI, AHI, and AGRI? I have a similar linear range for C08/C09/C10 (280K to 180K) for all 4 of these instruments.

Change default ABI C07 enhancement to linear 400.15K to 164.15K

---

integration_tests/features/environment.py
polar2grid/glue.py

Geo2Grid working directories were being deleted to make room for Polar2Grid tests, but I need to see those results when there are failures. This creates subdirectories for each set of tests.

Separate integration test working directories by feature name

---

polar2grid/etc/readers/mirs.yaml
polar2grid/readers/mirs.py

Closes #669 
Also adds --no-limb-correction command line flag and fixes issue where MiRS reader command line arguments were ignored.

Add custom MiRS reader configuration for duplicated NOAA-20 coeffs as NOAA-21

---

polar2grid/readers/viirs_edr.py

Closes #666. Adds a `--aod-qc-filter` flag to the `viirs_edr` reader that accepts 0/1/2/3 or "none" to filter AOD data by the QCAll quality flag.

Add VIIRS EDR AOD quality filter flag

---

continuous_integration/environment.yaml
jenkins_environment.yml

Sphinx-argparse is a third-party tool used to put our command line arguments from the python code into our documentation in a pretty way. It currently has a bug where section numbers are not kept unique between argparse blocks in a single page/document of the documentation. This PR updates Polar2Grid's build steps to use my not-yet-merged pull request code to sphinx-argparse where this is fixed (or at least worked around).
Closes #289

Switch to unstable sphinx-argparse for better documentation section numbers

---

NEWS.rst
polar2grid/readers/avhrr_l1b_aapp.py
polar2grid/readers/mersi2_l1b.py
polar2grid/readers/modis_l1b.py
polar2grid/readers/viirs_l1b.py
polar2grid/readers/viirs_sdr.py
pyproject.toml

Adds `--normalized-radiances` command line option to restore previous behavior. This PR updates various Polar2Grid readers to that visible channels have `/ cos(SZA)` applied to them by default. This means the results should be "real" reflectances rather than accidentally producing "normalized radiances".
Closes #707

Update readers to default to real reflectances

---

integration_tests/features/polar2grid.feature
polar2grid/readers/_base.py
polar2grid/readers/avhrr_l1b_aapp.py
polar2grid/tests/_avhrr_fixtures.py
polar2grid/tests/test_glue.py
polar2grid/utils/legacy_compat.py

New reflectances had satpy "modifiers" in their `DataID` identifier object. This made Polar2Grid think they weren't available from the reader, but technically they are. This PR changes it so we check for the modified version and if that doesn't exist in the reader, then we check for a lesser modified version of the dataset, and so on until there is a not modified version of the dataset that still isn't found in the reader.

Fix real reflectance products not showing in product list

---

.gitignore
MANIFEST.in
create_conda_software_bundle.sh
pyproject.toml

This is my initial attempt to switch the python package building system from setuptools (old, but classic library) to hatchling (new hotness). My hope is that besides using more modern tooling, I'm hoping I'll be able to restore the bundled bash scripts (see #728).

Update package build system to hatchling

---

polar2grid/etc/enhancements/generic.yaml
polar2grid/etc/writers/awips_tiled.yaml
polar2grid/readers/mirs.py

This pull request adds support for the MiRS Snow Grain Size product.  Both GeoTIFF and AWIPS tile production was tested successfully with these changes, using input from CSPP MiRS v4.0.  Below is a sample of a produced GeoTIFF with added colormap, title, geographic features, and colorbar using the included modifications to Polar2Grid:

Adds support for the MiRS Snow Grain Size product

---

NEWS.rst
polar2grid/core/containers.py
polar2grid/core/dtype.py
polar2grid/tests/test_dtype.py
polar2grid/writers/binary.py

If the output filename pattern specified by the user includes "data_type" it now becomes the numpy-style name of the data type. That means instead of the old "real4" you'll get "float32". If the output was for an 8-bit unsigned integer, instead of the old "uint1" it is now "uint8". This was mostly done for consistency and to reduce confusing code in the codebase.

Change binary writer to use numpy-style dtype names

---

NEWS.rst
polar2grid/glue.py
polar2grid/resample/_resample_scene.py

In future versions `.conf` grid configuration files will not be supported. This PR adds an explicit warning log message so hopefully users convert old configs to the new format in the next release or two.

Log deprecation warning when legacy '.conf' grid configurations are used

---

polar2grid/glue.py
polar2grid/writers/awips_tiled.py

I removed support for this from Satpy as it isn't needed in modern AWIPS.
This PR also includes fixing a deprecated keyword argument for dask's `visualize` diagnostics function.

Remove '--fix-awips' flag

---

polar2grid/core/script_utils.py
polar2grid/readers/acspo.py

This was previously always enabled and not user-controllable. Now there's a flag. Default is the same behavior.
Similar, but different flag, to #758.

Add --cloud-clear/--no-cloud-clear option to ACSPO reader

---

polar2grid/etc/enhancements/generic.yaml
polar2grid/glue.py
polar2grid/readers/abi_l1b.py
polar2grid/writers/binary.py

Closes #736 
Adds most of the RGBs in some form from the above mentioned issue. Excludes geo_color, sandwich, and day ocean cloud convection.
TODO:

Add new ABI RGBs to abi_l1b reader
