polar2grid/add_coastlines.py

This was a small change that someone asked me for in passing a while ago. Wasn't a huge deal to add so I added it.

Add '--borders-width' flag to add_coastlines.sh

---

polar2grid/add_coastlines.py

Closes #149 
I realized after adding #173 that there I should just add a flag for all the other widths. This PR does that.

Add coastline, river, and grid width arguments to add_coastlines.sh

---

doc/source/utilscripts.rst
polar2grid/add_coastlines.py
setup.py
swbundle/gtiff2mp4.sh
swbundle/overlay.sh

Closes #183. See this issue for more details.
I've also thrown in some small changes to `gtiff2mp4.sh` from Geo2Grid so that it might work with PNGs *and* TIFs. I forget his github username, but would be nice if Jim Nelson could test this out.
TODO:

Add overlay.sh for putting VIIRS Active Fires on top of other imagery

---

integration_tests/run.sh
jenkins_environment.yml

The doc environment needs polar2grid to make html and make pdf.

Add pip and polar2grid to Jenkins doc environment

---

polar2grid/readers/mersi2_l1b.py
polar2grid/readers/viirs_edr_active_fires.py
polar2grid/readers/virr_l1b.py

Includes removing longitude/latitude from available product list.
Closes #203

Set default VIIRS EDR Active Fires products

---

build_environment.yml
polar2grid/core/script_utils.py
polar2grid/glue_legacy.py
polar2grid/readers/__init__.py

@kathys pointed out that in the 2.3.0a2 tarball the mersi2_l1b reader doesn't generate the true_color composite. For some reason it delays the generation (sunz angle depending on 1000m angles) but never regenerates them after resampling is complete.
@kathys Feel free to add information here (test files, log file locations, etc) if you haven't already started an issue.

Fix MERSI-2 L1B generation of true_color RGB

---

.travis.yml
polar2grid/remap/_fornav_templates.cpp

Closes #242. See that issue for details.

Fix ll2cr again when handling NaN lon/lat values

---

polar2grid/debug_data.py

This adds a python script for debugging input data. However it depends on matplotlib and since we don't include that in our swbundle, I'm not sure how this can be run from the released product.

Add helper script for debugging input data

---

doc/source/examples/acspo_example.rst
doc/source/getting_started.rst
doc/source/introduction.rst
doc/source/readers/acspo.rst
doc/source/readers/crefl.rst
doc/source/summary_table.rst
doc/source/utilscripts.rst
doc/source/verification/modis_verification.rst
doc/source/verification/viirs_verification.rst
polar2grid/add_coastlines.py
polar2grid/avhrr/avhrr2swath.py
polar2grid/binary.py
polar2grid/gtiff_backend.py
polar2grid/hdf5_backend.py
polar2grid/mirs/mirs2swath.py
polar2grid/readers/mersi2_l1b.py
polar2grid/readers/viirs_edr_active_fires.py
polar2grid/readers/viirs_l1b.py
polar2grid/readers/virr_l1b.py
polar2grid/remap/remap.py
polar2grid/viirs/swath.py
polar2grid/writers/scmi.py

Missed a few things in the last PR #251

More documentation updates for P2G 2.3

---

NEWS.rst
doc/source/examples/acspo_example.rst
setup.py

Small doc fixes for the actual Polar2Grid 2.3.0 release.

Update release notes with P2G 2.3.0 release date

---

.travis.yml
NEWS_GEO2GRID.rst
doc/source/introduction.rst
polar2grid/readers/ahi_hrit.py
polar2grid/readers/ahi_hsd.py

Closes #258 
See https://github.com/pytroll/satpy/pull/1065 for example images.

Add AHI airmass, ash, dust, fog, and night_microphysics RGBs

---

Makefile
README.rst
create_conda_software_bundle.sh

It isn't used anymore. See #292. Closes #292.

Remove old re_upload script for RealEarth

---

polar2grid/gtiff_backend.py

Fix typo in dtype flag for gtiff backend

---

etc/composites/viirs.yaml
etc/enhancements/viirs.yaml
polar2grid/glue.py
polar2grid/readers/amsr2_l2_gaasp.py
polar2grid/readers/viirs_sdr.py
polar2grid/writers/awips_tiled.py
polar2grid/writers/geotiff.py
polar2grid/writers/scmi.py

Uses Satpy's `amsr2_l2_gaasp` reader. Includes some other VIIRS SDR fixes and more preparation for Polar2Grid 3.0.

Add initial Polar2Grid 3.0 AMSR2 L2 GAASP Reader

---

doc/source/_static/G2G Logo.psd
doc/source/_static/G2G_PDF_Logos.png
doc/source/_static/P2G Logo.psd
doc/source/_static/P2G_PDF_Logos.png

Update PDF title logos to include CSPP logo

---

.gitignore
NEWS.rst
continuous_integration/environment.yaml
doc/source/conf.py
doc/source/design_overview.rst
doc/source/dev_guide/adding_readers.rst
doc/source/dev_guide/dev_env.rst
doc/source/dev_guide/index.rst
doc/source/dev_guide/json_input.rst
doc/source/dev_guide/swbundle.rst
doc/source/index.rst
doc/source/introduction.rst
doc/source/overview.rst
doc/source/rescaling.rst
jenkins_environment.yml
polar2grid/avhrr/readers.py
setup.py

This should help new contributors add readers to Polar2Grid and Geo2Grid.
FYI @kathys and @nbearson

Add initial draft of adding new readers documentation

---

polar2grid/compare.py

As far as I can tell, the `polar2grid.compare` script which is used by the integration tests does not automatically find all variables in a NetCDF or HDF5 file to be compared. You must provide them. This isn't super flexible so this PR makes it discover what should be compared if the list of variables is not provided.

Add ability for compare script to compare all NC/HDF5 variables

---

etc/enhancements/generic.yaml

This ports "rescale" configurations from the legacy P2G to new P2G's Satpy enhancement configuration YAML files.

Add missing MiRS specific enhancement configurations

---

polar2grid/core/script_utils.py
polar2grid/writers/geotiff.py

Allows for --tiled (default) or --no-tiled

Switch geotiff writer to tile by default

---

doc/source/readers/viirs_edr_active_fires.rst
doc/source/readers/viirs_edr_flood.rst
etc/resampling.yaml
polar2grid/readers/viirs_edr_active_fires.py
polar2grid/readers/viirs_edr_flood.py
polar2grid/resample/_resample_scene.py

Port VIIRS EDR Active Fires and Flood readers for Polar2Grid 3.0

---

doc/source/readers/amsr2_l1b.rst
polar2grid/readers/amsr2_l1b.py
polar2grid/readers/amsr2_l2_gaasp.py

Port AMSR2 L1B and AMSR L2 GAASP readers for Polar2Grid 3.0

---

doc/source/readers/acspo.rst
etc/resampling.yaml
polar2grid/readers/acspo.py

Port ACSPO SST reader for Polar2Grid 3.0

---

polar2grid/compare.py

Some geotiffs have colormaps. Now not only are the image arrays compared but the actual colormap data.

Add geotiff colormap comparison to compare scripts

---

polar2grid/glue.py
polar2grid/tests/test_glue.py

Introduced by #407 
I'm not sure how to easily write a unit test for this given the current test setup I have. I don't currently do any full system tests in pytest.

Fix products kwarg not being popped

---

polar2grid/tests/conftest.py
polar2grid/tests/test_writers/test_hdf5.py
polar2grid/writers/hdf5.py

Includes new tests for the HDF5 writer.

Refactor HDF5 writer to be less complex

---

.github/workflows/ci.yaml
build_environment.yml
continuous_integration/environment.yaml
doc/source/conf.py
doc/source/dev_guide/adding_readers.rst
doc/source/readers/agri_l1.rst
doc/source/readers/ami_l1b.rst
doc/source/readers/index.rst
etc/enhancements/agri.yaml
etc/enhancements/ami.yaml
polar2grid/add_coastlines.py
polar2grid/glue.py
polar2grid/readers/abi_l1b.py
polar2grid/readers/agri_l1.py
polar2grid/readers/ami_l1b.py
polar2grid/tests/conftest.py
polar2grid/tests/test_glue.py
polar2grid/writers/geotiff.py

This PR is based on #426 which should be merged first. This adds the `agri_l1` reader...or at least an initial version.

Add AGRI L1 (agri_l1) reader

---

polar2grid/compare.py
polar2grid/tests/test_compare.py
polar2grid/tests/test_main.py

Noticed that the compare script and the `__main__` script are completely uncovered. This PR adds unit tests for them for future modifications/features.

Add tests for main and compare script

---

etc/writers/awips_tiled.yaml
polar2grid/glue.py
polar2grid/readers/mirs.py

* Missing products, Closes #508
* Incorrect physical elements in AWIPS tiled writer, Closes #510
* Bad satellite naming in filenames, Closes #509
CC @joleenf

Fix various MiRS reader issues

---

etc/resampling.yaml

Closes #521. Read that issue for more details.

Add resampling section for AMSR2

---

continuous_integration/environment.yaml
integration_tests/features/steps/compare_images.py
integration_tests/features/utilities.feature
swbundle/gtiff2kmz.sh

Fix gtiff2kmz.sh having invalid path to gdal2tiles.py script

---

build_environment.yml
polar2grid/writers/binary.py

Reword binary writer command line flags descriptions

---

polar2grid/filters/_base.py
polar2grid/tests/test_filters/test_day_night.py

Closes #544 
This PR makes sure that composites that are filtered are removed from the wishlist of products to be made later.

Fix some composites being filtered and then regenerated

---

polar2grid/grids/manager.py

Noticed that some code quality utilities were complaining about this module so I thought I'd do something about it.

Cleanup grid manager code

---

.github/workflows/deploy-sdist.yaml
Makefile
NEWS_GEO2GRID.rst
doc/source/index.rst
polar2grid/add_coastlines.py
polar2grid/tests/test_add_coastlines.py

Also adds new --colorbar-minor-tick-marks to control number of minor ticks in a colorbar.
Closes #575 
Closes #573

Fix multiple inputs to coastlines when adding colormaps

---

polar2grid/tests/test_filters/test_utils.py

Pyresample 1.26.1 made this more accurate and doesn't repeat the endpoints. This is just updating the tests. None of the actual processing code changed.

Update expected test values for boundaries of geostationary data

---

NEWS.rst

Really, this is the last change!

Final minor cleanup of the P2G Version 3.0 What's New section.

---

polar2grid/etc/enhancements/generic.yaml

No real effect, but still confusing.

Fix typo in generic.yaml

---

polar2grid/readers/fci_l1c_nc.py

Fix missing FCI ir_38 channel

---

polar2grid/utils/config.py

Fix package config not being set properly in non-bundle environments

---

.github/workflows/ci.yaml
polar2grid/readers/avhrr_l1b_aapp.py

Fix an issue introduced in #714

Fix AVHRR reader not creating reflectance aliases properly

---

swbundle/env.sh

Ensure bundle scripts have priority over python package scripts

---

polar2grid/_glue_argparser.py
polar2grid/glue.py
polar2grid/tests/test_glue.py

Improve error message and handling of unknown writers

---

polar2grid/etc/enhancements/abi.yaml
polar2grid/readers/abi_l2_nc.py
polar2grid/resample/resample_decisions.py
polar2grid/utils/config.py

Add Phase and PRES to 'abi_l2_nc' reader

---

polar2grid/etc/enhancements/amsr2.yaml
polar2grid/etc/enhancements/generic.yaml

Closes #742
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>

Add updated AMSR2 GAASP enhancements

---

doc/source/conf.py
doc/source/readers/avhrr.rst
doc/source/readers/aws1_mwr_l1b_nc.rst
doc/source/readers/index.rst
polar2grid/etc/composites/ahi.yaml
polar2grid/etc/resampling.yaml
polar2grid/readers/aws1_mwr_l1b_nc.py

Closes #755
Documentation could use updating.

Add AWS1 MWR reader

---

polar2grid/glue.py

This is to clear things up for users of the @graemely variety who take code snippets from documentation without reading the surrounding text...
This fixes the error message(s) shown when a user requests a product that doesn't exist or that they have mistyped. It should now look like:
```bash
$ geo2grid -r abi_l1b -w geotiff -p true_color_night_microphysics -f /data/satellite/abi/20170920/*.nc
ERROR    : Unknown product requested:
true_color_night_microphysics
```
If needed in the future this can get even more detailed. Satpy provides an exception object that has all the missing dependencies for each requested product. So if one composite is missing something and another composite is missing something else, those show up as separate "set" objects. For now, I've just flattened the whole …

Add cleaner error message when unknown product names are requested

---

build_environment.yml
create_conda_software_bundle.sh

Ex. Remove "polar2grid.sh" when building Geo2Grid

Remove project specific scripts from software bundle of other project
